version: "3.0"
services:
  run:
    build: .
  run-gunicorn:
    build:
      dockerfile: Dockerfile.gunicorn
      context: .
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
  test:
    image: python:3.8
    volumes:
      - .:/code
    working_dir: /code
    command:
      - bash
      - -c
      - pip install tox; tox
