openapi: 3.0.0
info:
  version: 0.0.1
  title: Ontopia core vocabularies
  description: |-
    recupera i dati dei vocabolari da ontopia
servers:
- url: >-
   /vocabolari/v0
  description: dev
paths:
  /status:
    get:
      summary: Service status
      operationId: ontopia.get_status
      responses:
        "200":
          description: tottok
          content:
            application/json:
              schema:
                type: object

  /vocabolari:
    get:
      summary: List vocabularies
      operationId: ontopia.get_datasets
      responses:
        "200":
          description: A list of dataset
          content:
            application/json:
              schema:
                type: object
                required:
                  - _links
                properties:
                  _links:
                      type: object
                additionalProperties: true

  /vocabolari/{classification}/{vocabulary_name}:
    get:
      summary: il voc
      parameters:
      - name: classification
        in: path
        required: true
        schema: {type: string, pattern: '[a-zA-Z]+', example: 'classifications-for-documents' }
      - name: vocabulary_name
        in: path
        required: true
        schema: {type: string, pattern: '[a-zA-Z]+', example: 'government-documents-types' }
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 200
          minimum: 0
          maximum: 200
          format: int32
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          default: 0
          minimum: 0
          maximum: 10000
          format: int32

      operationId: ontopia.get_vocabulary
      responses:
        "200":
           description: tottok
           content:
             application/json:
               schema:
                 type: object
