openapi: 3.0.0
info:
  version: 0.0.1
  title: Ontopia Vocabolari Controllati
  description: |-
    Espone i vocabolari controllati presenti in  Ontopia in formato mobile-ready
    permettendo di usare i contenuti dei vocabolari per creare form web ed applicazioni.

    I vocabolari controllati contengono una serie di informazioni di pubblica utilità
    come:
    - l'elenco delle province con i relativi codici ISTAT;
    - le tipologie dei titoli di studio o i titoli accademici (eg. "Assistente", "Professore associato", ..)
    - le tipologie di documenti ("Modulistica", "Atto normativo", ..)
    - i titoli delle persone ("Sig.ra", "Dott", "Prof.ssa", ..).

    Queste informazioni utili a comporre dei servizi pubblici, sono spesso utilizzate con
    sintassi differenti o in maniera impropria: tramite i vocabolari è possibile invece
    attingere a queste informazioni direttamente dai contenuti di Ontopia.
  x-summary: >-
    API che espone gli elenchi (Comuni, Province, titoli di studio, ..) contenuti nei Vocabolari Controllati di Ontopia.
  x-api-id: bbf68f14-622f-4821-9723-1c88423d893f
  contact:
    name: AgID
    url: https://www.agid.gov.it/it/dati/vocabolari-controllati
  termsOfService: https://www.agid.gov.it/it/note-legali
x-commons:
  common-responses: &common-responses
    default:
      $ref: "https://teamdigitale.github.io/openapi/0.0.6/definitions.yaml#/responses/default"

servers:
- url: >-
   /vocabolari/v0
  description: dev
paths:
  /status:
    get:
      summary: Service status
      operationId: ontopia.get_status
      responses:
        <<: *common-responses
        "200":
          description: Everything is ok.
          content:
            application/json:
              schema:
                $ref: "https://teamdigitale.github.io/openapi/0.0.6/definitions.yaml#/schemas/Problem"

  /vocabolari:
    get:
      summary: Elenca i vocabolari disponibili
      operationId: ontopia.get_datasets
      responses:
        <<: *common-responses
        "200":
          description: |-
            La ricerca dei vocabolari è andata a buon fine.
          content:
            application/json:
              schema:
                type: object
                required:
                  - _links
                  - items
                properties:
                  _links:
                    $ref: '#/components/schemas/Limit'
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          maxLength: 128
                        uri:
                          $ref: '#/components/schemas/Url'


  /vocabolari/{classification}/{vocabulary_name}:
    get:
      summary: Recupera un vocabolario.
      parameters:
      - name: classification
        in: path
        required: true
        schema: {type: string, pattern: '[a-zA-Z]+', example: 'classifications-for-documents' }
      - name: vocabulary_name
        in: path
        required: true
        schema: {type: string, pattern: '[a-zA-Z]+', example: 'government-documents-types' }
      - name: limit
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/Limit'
      - name: offset
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/Offset'
      operationId: ontopia.get_vocabulary
      responses:
        <<: *common-responses
        "200":
           description: |-
             Ritorna il contenuto di un vocabolario. In caso di problemi nella visualizzazione
             del vocabolario è possibile fare un raffronto con
             [i contenuti dell'ontologia presenti su github](https://github.com/italia/daf-ontologie-vocabolari-controllati)
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/Vocabulary'
components:
  schemas:
    Url:
      type: string
      format: url
      maxLength: 1024
    Limit:
      type: integer
      default: 200
      minimum: 0
      maximum: 200
      format: int32
    Offset:
      type: integer
      default: 0
      minimum: 0
      maximum: 10000
      format: int32
    PagedResponse:
      description: Una risposta paginata
      properties:
        count:
          $ref: '#/components/schemas/Limit'
        limit:
          $ref: '#/components/schemas/Limit'
        offset_next:
          $ref: '#/components/schemas/Offset'
        page_next:
          $ref: '#/components/schemas/Url'
    Links:
      properties:
        count:
          $ref: '#/components/schemas/Limit'
        limit:
          $ref: '#/components/schemas/Limit'
        offset_next:
          $ref: '#/components/schemas/Offset'
        page_next:
          $ref: '#/components/schemas/Url'
        query:
          description: |-
            La query SPARQL usata per recuperare i dati da ontopia.
          type: array
          items:
            type: string
            maxLength: 512
        url:
          $ref: '#/components/schemas/Url'
    Vocabulary:
      description: |-
        Un vocabolario composto da una serie di metadati contenuti in `_links` e dai contenuti localizzati (eg. it, en).
      required:
        - _links
      properties:
        "_links":
          $ref: "#/components/schemas/Links"
      additionalProperties:
        description: |-
          Il nome di queste proprietà è un "alpha-2 country code" come citato
          in [BCP47](https://tools.ietf.org/html/bcp47).
        type: string
        pattern: '[a-z]{2}'
